apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.component }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::512646826903:role/{{ .values.env }}-roboshop-eks-pod-role-for-{{ .values.component }}-ssm-parameters

